name: CI_TECSUnit

on:
  push:
    branches:
      - workspace

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: set env
        run: |
          cd hr-tecs/tecsgen
          echo "TECSPATH=$PWD/tecsgen/tecs" >> $GITHUB_ENV
          
      - name: make
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          make
          
  execution:
    needs: make
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: execution
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          ls
          
