name: CI_TECSUnit

on:
  push:
    branches:
      - workspace

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: set env
        run: |
          cd hr-tecs/tecsgen
          echo "TECSPATH=$PWD/tecsgen/tecs" >> $GITHUB_ENV
          
      - name: make
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          make
      
      - name: execution
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          ./TECSUnit.exe
          
      - name: coverage
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          gcov gen/*.gcda
          cat *.gcov >> $GITHUB_STEP_SUMMARY
          
