name: CI_TECSUnit

on:
  push:
    branches:
      - workspace

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: set env
        run: |
          cd hr-tecs/tecsgen
          echo "TECSPATH=$PWD/tecsgen/tecs" >> $GITHUB_ENV
          
      - name: make
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          make
      
      - name: execution
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          ./TECSUnit.exe
      
      - name: test result
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          cat test_result.txt >> SUMMARY.md
          
      - name: coverage
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          gcov -f gen/*.gcda >> coverage_results.txt
          ruby coverage_results.rb >> SUMMARY.md
          cat *.gcov
      
      - name: Convert SUMMARY to HTML
        run: |
          sudo apt-get install pandoc
          pandoc --version
          pandoc -s -o SUMMARY.html hr-tecs/tecsgen/TECSUnit/SUMMARY.md
          sed -i 's/<td>/<td bgcolor="lightgreen">/g' SUMMARY.html
          
      - name: Deploy HTML file
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          
