name: CI_TECSUnit

on: [push]

jobs:
  TECSUnit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: set env
        run: |
          cd hr-tecs/tecsgen
          echo "TECSPATH=$PWD/tecsgen/tecs" >> $GITHUB_ENV
      
      - name: test
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          echo "hello"
      
      - name: make tecs
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          make tecs
          
      - name: make
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          make
          
      - name: exe
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          ./TECSUnit.exe
