name: TECSUnit Test

on:
  push:
    branches:
      - workspace

jobs:
  build:
    runs-on: Ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Environment
        run: |
          cd hr-tecs/tecsgen/
          source set_env.sh
      
      - name: Build & Test
        run: |
          cd hr-tecs/tecsgen/TECSUnit
          make tecs
          make
          ./TECSUnit.exe
